package com.wgsoft.game.timesaver;

public class Const {
    public static MyGdxGame game;

    public static final int GAME_BUILDING_COUNT = 4;
    public static final int GAME_PLAYER_FULLNESS_LEVEL_MAX = 5;
    public static final int GAME_PLAYER_STATE_COUNT = 4;

    public static final float SCREEN_WIDTH = 1920;
    public static final float SCREEN_HEIGHT = 1080;
    public static final float MENU_BUTTON_PADDING = 50f;
    public static final float GAME_BUTTON_PADDING_HORIZONTAL = 60f;
    public static final float GAME_BUTTON_PADDING_TOP = 50f;
    public static final float GAME_PLAYER_MAX_TIME_DEFAULT = 5f;
    public static final float GAME_TIME_PROGRESS_BAR_STEP = 0.005f;
    public static final float GAME_BUBBLE_SIZE_MIN = 450f;
    public static final float GAME_BUBBLE_SIZE_MAX = 1400f;
    public static final float GAME_PLAYER_FRAME_DURATION = 0.1f;
    public static final float GAME_UNIT_SIZE = 250f;
    public static final float GAME_PLAYER_WIDTH_SCALE = 0.55f;
    public static final float GAME_PLAYER_HEIGHT_SCALE = 0.6f;
    public static final float GAME_PLAYER_SPEED = 500f;
    public static final float GAME_PLAYER_SPRINT_SCALE = 1.5f;
    public static final float GAME_BUILDINGS_PARALLAX = 0.5f;
    public static final float GAME_BORDER_LEFT = -960f;
    public static final float GAME_BORDER_RIGHT = 9360f;
    public static final float GAME_GRAVITY = 1500f;
    public static final float GAME_PLAYER_JUMP_IMPULSE = 1300f;
    public static final float GAME_PLAYER_DOWN_IMPULSE = -500f;
    public static final float GAME_TIME_OVER_ANIMATION_DURATION = 3f;
    public static final float GAME_PLAYER_ATTACK_DURATION = 0.25f;
    public static final float GAME_PLAYER_ATTACK_SPEED = 2000f;
    public static final float GAME_PLAYER_ATTACK_TIME_CONSUME_SPEED = 10f;
    public static final float GAME_PLAYER_STATE_ALPHA_SPEED = 2f;
    public static final float GAME_THROWABLE_SIZE = 62.5f;
    public static final float GAME_TIME_MINE_SPEED = 2000f;
    public static final float GAME_TIME_MINE_SHIFT_INTERVAL = 0.2f;
    public static final float GAME_TIME_MINE_SHIFT_AMPLITUDE = 50f;
    public static final float GAME_TIME_MINE_TIME_CONSUMPTION = 0.5f;
    public static final float GAME_TIME_FILL_SOUND_DELAY = 2f;
    public static final float GAME_SCIENTIST_WIDTH_SCALE = 0.5f;
    public static final float GAME_SCIENTIST_HEIGHT_SCALE = 1f;
    public static final float GAME_SCIENTIST_STAY_FRAME_DURATION = 0.5f;
    public static final float GAME_SCIENTIST_DIE_FRAME_DURATION = 0.1f;
    public static final float GAME_SCIENTIST_RUN_FRAME_DURATION = 0.4f;
    public static final float GAME_SCIENTIST_ATTACK_FRAME_DURATION = 0.2f;
    public static final float GAME_MONSTER_DEATH_MAX_TIME_BONUS = 0.5f;
    public static final float GAME_MONSTER_VISIBLE_RADIUS = 960f;
    public static final float GAME_SCIENTIST_SPEED = 100f;
    public static final float GAME_BOTTLE_ROTATION_SPEED_AMPLITUDE = 180f;
    public static final float GAME_BOTTLE_SPEED = 500f;
    public static final float GAME_BOTTLE_IMPULSE = 500f;
    public static final float GAME_OUTSIDE_BUBBLE_SPEED_SCALE = 0.4f;
    public static final float GAME_SCIENTIST_ATTACK_INTERVAL = 1f;
    public static final float GAME_DRUG_DEALER_WIDTH_SCALE = 0.5f;
    public static final float GAME_DRUG_DEALER_HEIGHT_SCALE = 0.8f;
    public static final float GAME_DRUG_DEALER_STAY_FRAME_DURATION = 0.4f;
    public static final float GAME_DRUG_DEALER_ATTACK_FRAME_DURATION = 0.3f;
    public static final float GAME_DRUG_DEALER_DIE_FRAME_DURATION = 0.1f;
    public static final float GAME_DRUG_DEALER_ATTACK_INTERVAL = 1f;
    public static final float GAME_DRUG_ROTATION_SPEED_AMPLITUDE = 180f;
    public static final float GAME_DRUG_SPEED = 700f;
    public static final float GAME_DRUG_IMPULSE = 700f;
    public static final float GAME_EYE_WIDTH_SCALE = 0.8f;
    public static final float GAME_EYE_HEIGHT_SCALE = 0.8f;
    public static final float GAME_EYE_FLY_FRAME_DURATION = 0.2f;
    public static final float GAME_EYE_DIE_FRAME_DURATION = 0.1f;
    public static final float GAME_EYE_ACCELERATION = 500f;
    public static final float GAME_SHOP_WIDTH_SCALE = 0.8f;
    public static final float GAME_SHOP_HEIGHT_SCALE = 1f;
    public static final float GAME_TRUCK_WIDTH_SCALE = 0.65f;
    public static final float GAME_TRUCK_HEIGHT_SCALE = 1f;
    public static final float GAME_TRUCK_MAX_OFFSET = 50f;
    public static final float GAME_PORTAL_WIDTH = 250f;
    public static final float GAME_PORTAL_HEIGHT = 375f;
    public static final float GAME_PORTAL_STAY_FRAME_DURATION = 0.2f;
    public static final float GAME_PORTAL_SHRINK_FRAME_DURATION = 0.1f;
    public static final float GAME_PLAYER_TIME_FILL_DURATION = 1f;
    public static final float GAME_HATCH_WIDTH = 250f;
    public static final float GAME_HATCH_HEIGHT = 250f;
    public static final float GAME_HATCH_MOVE_DURATION = 3f;
    public static final float GAME_PLAYER_MOVE_DURATION = 1f;
    public static final float GAME_PLAYER_DOWN_DURATION = 1f;
    public static final float SETTINGS_SOUND_DEFAULT = 0.5f;
    public static final float SETTINGS_MUSIC_DEFAULT = 0.5f;

    public static final String[] SETTINGS_LANGUAGES = new String[]{
            "en"
    };
}
